
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'agan_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'agan_dbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

on-run-end:
  - "{{ grant_create('analytics_objects', 'master') }}"
  - "{{ grant_read('analytics_objects', 'master') }}"


#  - "{{ grant_read('analytics_reports', 'metabase_read') }}"
#  - "{{ grant_read('analytics_reports', 'metabase_analytics') }}"
#  - "{{ grant_read('analytics_reporting', 'metabase_analytics') }}"
#  - "{{ grant_create('analytics_reporting', 'metabase_analytics') }}"
#  - "{{ grant_create('analytics_reports', 'metabase_analytics') }}"
#  - "{{ grant_read('analytics_objects', 'metabase_analytics') }}"
#  - "{{ grant_read('analytics_calc', 'metabase_analytics') }}"
#  - "{{ grant_read('raw_google_analytics', 'metabase_analytics') }}"
#  - "{{ grant_read('raw_scanpoint', 'metabase_analytics') }}"
#  - "{{ grant_read('raw_adamant', 'metabase_analytics') }}"
#  - "{{ grant_read('raw_wkfs', 'metabase_analytics') }}"
#  - "{{ grant_read('analytics_reporting', 'metabase_read') }}"

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  agan_dbt:
    # Config indicated by + and applies to all files under models/example/
    +sql_header: "SET TIMEZONE TO 'UTC';"
    +schema: bin # default if nothing else is specified
    +materialized: table

    example:
      +schema: objects
      +materialized: view

    objects:
      +schema: objects
#      +materialized: table

    calculations:
      +schema: calculations
#      +materialized: table