agan_dbt:
  outputs:
    dev:
      type: redshift
      threads: 8
      host: data-warehouse-test.cok4yrt2nbyk.eu-central-1.redshift.amazonaws.com
      port: 5432
      user: master
      pass: 'aGAN321.'
      dbname: dwh
      schema: object # e.g. dbt_alice
  target: dev
config:
  send_anonymous_usage_stats: false
  use_colors: false


