name: Build image for Production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Files
        uses: actions/checkout@v2

      - name: new ssh proxy
        uses: appleboy/ssh-action@master
        with:
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.HOST_DNS }}
          proxy_username: ${{ secrets.USERNAME }}
          host: "10.0.0.231"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ls -ltra &&
            whoami && cd .. && rm -rf airflow_test 2> /dev/null &&
            pwd && sudo git clone https://github.com/psalmprax/airflow_test.git && ls -ltra
#            && cd airflow_test
#            && sudo docker-compose up --build -d
#            sudo docker-compose down -v && sudo docker system prune -a -f &&
